nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"
enableScripts: true

packageExtensions:
  pdfjs-dist@*:
    dependencies:
      canvas: "*"
    peerDependencies:
      canvas: "*"
    peerDependenciesMeta:
      canvas:
        optional: true 